<?php

namespace ContainerD5JFcxX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllCitiesForecastCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Presentation\Cli\AllCitiesForecastCommand' shared autowired service.
     *
     * @return \App\Presentation\Cli\AllCitiesForecastCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Presentation/Cli/AllCitiesForecastCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Service/City/CityService.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Model/City/CityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Domain/Model/City/ApiCityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/Client.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Http/HttpQueryClientInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Http/HttpQueryClient.php';

        $container->privates['App\\Presentation\\Cli\\AllCitiesForecastCommand'] = $instance = new \App\Presentation\Cli\AllCitiesForecastCommand(new \App\Application\Service\City\CityService(new \App\Infrastructure\Domain\Model\City\ApiCityRepository(new \App\Infrastructure\Http\HttpQueryClient())));

        $instance->setName('app:all-cities-forecast');

        return $instance;
    }
}
