<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxBqafo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxBqafo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAxBqafo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAxBqafo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAxBqafo\App_KernelDevDebugContainer([
    'container.build_hash' => 'AxBqafo',
    'container.build_id' => '9c6ba0b6',
    'container.build_time' => 1609245825,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxBqafo');
